<?php

namespace Database\Seeders;

use App\Models\Regency;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RegencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Regency::create(["id" => 1101, "province_id" => 11, "name" => 'KAB. ACEH SELATAN']);
        Regency::create(["id" => 1102, "province_id" => 11, "name" => 'KAB. ACEH TENGGARA']);
        Regency::create(["id" => 1103, "province_id" => 11, "name" => 'KAB. ACEH TIMUR']);
        Regency::create(["id" => 1104, "province_id" => 11, "name" => 'KAB. ACEH TENGAH']);
        Regency::create(["id" => 1105, "province_id" => 11, "name" => 'KAB. ACEH BARAT']);
        Regency::create(["id" => 1106, "province_id" => 11, "name" => 'KAB. ACEH BESAR']);
        Regency::create(["id" => 1107, "province_id" => 11, "name" => 'KAB. PIDIE']);
        Regency::create(["id" => 1108, "province_id" => 11, "name" => 'KAB. ACEH UTARA']);
        Regency::create(["id" => 1109, "province_id" => 11, "name" => 'KAB. SIMEULUE']);
        Regency::create(["id" => 1110, "province_id" => 11, "name" => 'KAB. ACEH SINGKIL']);
        Regency::create(["id" => 1111, "province_id" => 11, "name" => 'KAB. BIREUEN']);
        Regency::create(["id" => 1112, "province_id" => 11, "name" => 'KAB. ACEH BARAT DAYA']);
        Regency::create(["id" => 1113, "province_id" => 11, "name" => 'KAB. GAYO LUES']);
        Regency::create(["id" => 1114, "province_id" => 11, "name" => 'KAB. ACEH JAYA']);
        Regency::create(["id" => 1115, "province_id" => 11, "name" => 'KAB. NAGAN RAYA']);
        Regency::create(["id" => 1116, "province_id" => 11, "name" => 'KAB. ACEH TAMIANG']);
        Regency::create(["id" => 1117, "province_id" => 11, "name" => 'KAB. BENER MERIAH']);
        Regency::create(["id" => 1118, "province_id" => 11, "name" => 'KAB. PIDIE JAYA']);
        Regency::create(["id" => 1171, "province_id" => 11, "name" => 'KOTA BANDA ACEH']);
        Regency::create(["id" => 1172, "province_id" => 11, "name" => 'KOTA SABANG']);
        Regency::create(["id" => 1173, "province_id" => 11, "name" => 'KOTA LHOKSEUMAWE']);
        Regency::create(["id" => 1174, "province_id" => 11, "name" => 'KOTA LANGSA']);
        Regency::create(["id" => 1175, "province_id" => 11, "name" => 'KOTA SUBULUSSALAM']);
        Regency::create(["id" => 1201, "province_id" => 12, "name" => 'KAB. TAPANULI TENGAH']);
        Regency::create(["id" => 1202, "province_id" => 12, "name" => 'KAB. TAPANULI UTARA']);
        Regency::create(["id" => 1203, "province_id" => 12, "name" => 'KAB. TAPANULI SELATAN']);
        Regency::create(["id" => 1204, "province_id" => 12, "name" => 'KAB. NIAS']);
        Regency::create(["id" => 1205, "province_id" => 12, "name" => 'KAB. LANGKAT']);
        Regency::create(["id" => 1206, "province_id" => 12, "name" => 'KAB. KARO']);
        Regency::create(["id" => 1207, "province_id" => 12, "name" => 'KAB. DELI SERDANG']);
        Regency::create(["id" => 1208, "province_id" => 12, "name" => 'KAB. SIMALUNGUN']);
        Regency::create(["id" => 1209, "province_id" => 12, "name" => 'KAB. ASAHAN']);
        Regency::create(["id" => 1210, "province_id" => 12, "name" => 'KAB. LABUHANBATU']);
        Regency::create(["id" => 1211, "province_id" => 12, "name" => 'KAB. DAIRI']);
        Regency::create(["id" => 1212, "province_id" => 12, "name" => 'KAB. TOBA SAMOSIR']);
        Regency::create(["id" => 1213, "province_id" => 12, "name" => 'KAB. MANDAILING NATAL']);
        Regency::create(["id" => 1214, "province_id" => 12, "name" => 'KAB. NIAS SELATAN']);
        Regency::create(["id" => 1215, "province_id" => 12, "name" => 'KAB. PAKPAK BHARAT']);
        Regency::create(["id" => 1216, "province_id" => 12, "name" => 'KAB. HUMBANG HASUNDUTAN']);
        Regency::create(["id" => 1217, "province_id" => 12, "name" => 'KAB. SAMOSIR']);
        Regency::create(["id" => 1218, "province_id" => 12, "name" => 'KAB. SERDANG BEDAGAI']);
        Regency::create(["id" => 1219, "province_id" => 12, "name" => 'KAB. BATU BARA']);
        Regency::create(["id" => 1220, "province_id" => 12, "name" => 'KAB. PADANG LAWAS UTARA']);
        Regency::create(["id" => 1221, "province_id" => 12, "name" => 'KAB. PADANG LAWAS']);
        Regency::create(["id" => 1222, "province_id" => 12, "name" => 'KAB. LABUHANBATU SELATAN']);
        Regency::create(["id" => 1223, "province_id" => 12, "name" => 'KAB. LABUHANBATU UTARA']);
        Regency::create(["id" => 1224, "province_id" => 12, "name" => 'KAB. NIAS UTARA']);
        Regency::create(["id" => 1225, "province_id" => 12, "name" => 'KAB. NIAS BARAT']);
        Regency::create(["id" => 1271, "province_id" => 12, "name" => 'KOTA MEDAN']);
        Regency::create(["id" => 1272, "province_id" => 12, "name" => 'KOTA PEMATANGSIANTAR']);
        Regency::create(["id" => 1273, "province_id" => 12, "name" => 'KOTA SIBOLGA']);
        Regency::create(["id" => 1274, "province_id" => 12, "name" => 'KOTA TANJUNG BALAI']);
        Regency::create(["id" => 1275, "province_id" => 12, "name" => 'KOTA BINJAI']);
        Regency::create(["id" => 1276, "province_id" => 12, "name" => 'KOTA TEBING TINGGI']);
        Regency::create(["id" => 1277, "province_id" => 12, "name" => 'KOTA PADANG SIDEMPUAN']);
        Regency::create(["id" => 1278, "province_id" => 12, "name" => 'KOTA GUNUNGSITOLI']);
        Regency::create(["id" => 1301, "province_id" => 13, "name" => 'KAB. PESISIR SELATAN']);
        Regency::create(["id" => 1302, "province_id" => 13, "name" => 'KAB. SOLOK']);
        Regency::create(["id" => 1303, "province_id" => 13, "name" => 'KAB. SIJUNJUNG']);
        Regency::create(["id" => 1304, "province_id" => 13, "name" => 'KAB. TANAH DATAR']);
        Regency::create(["id" => 1305, "province_id" => 13, "name" => 'KAB. PADANG PARIAMAN']);
        Regency::create(["id" => 1306, "province_id" => 13, "name" => 'KAB. AGAM']);
        Regency::create(["id" => 1307, "province_id" => 13, "name" => 'KAB. LIMA PULUH KOTA']);
        Regency::create(["id" => 1308, "province_id" => 13, "name" => 'KAB. PASAMAN']);
        Regency::create(["id" => 1309, "province_id" => 13, "name" => 'KAB. KEPULAUAN MENTAWAI']);
        Regency::create(["id" => 1310, "province_id" => 13, "name" => 'KAB. DHARMASRAYA']);
        Regency::create(["id" => 1311, "province_id" => 13, "name" => 'KAB. SOLOK SELATAN']);
        Regency::create(["id" => 1312, "province_id" => 13, "name" => 'KAB. PASAMAN BARAT']);
        Regency::create(["id" => 1371, "province_id" => 13, "name" => 'KOTA PADANG']);
        Regency::create(["id" => 1372, "province_id" => 13, "name" => 'KOTA SOLOK']);
        Regency::create(["id" => 1373, "province_id" => 13, "name" => 'KOTA SAWAHLUNTO']);
        Regency::create(["id" => 1374, "province_id" => 13, "name" => 'KOTA PADANG PANJANG']);
        Regency::create(["id" => 1375, "province_id" => 13, "name" => 'KOTA BUKITTINGGI']);
        Regency::create(["id" => 1376, "province_id" => 13, "name" => 'KOTA PAYAKUMBUH']);
        Regency::create(["id" => 1377, "province_id" => 13, "name" => 'KOTA PARIAMAN']);
        Regency::create(["id" => 1401, "province_id" => 14, "name" => 'KAB. KAMPAR']);
        Regency::create(["id" => 1402, "province_id" => 14, "name" => 'KAB. INDRAGIRI HULU']);
        Regency::create(["id" => 1403, "province_id" => 14, "name" => 'KAB. BENGKALIS']);
        Regency::create(["id" => 1404, "province_id" => 14, "name" => 'KAB. INDRAGIRI HILIR']);
        Regency::create(["id" => 1405, "province_id" => 14, "name" => 'KAB. PELALAWAN']);
        Regency::create(["id" => 1406, "province_id" => 14, "name" => 'KAB. ROKAN HULU']);
        Regency::create(["id" => 1407, "province_id" => 14, "name" => 'KAB. ROKAN HILIR']);
        Regency::create(["id" => 1408, "province_id" => 14, "name" => 'KAB. SIAK']);
        Regency::create(["id" => 1409, "province_id" => 14, "name" => 'KAB. KUANTAN SINGINGI']);
        Regency::create(["id" => 1410, "province_id" => 14, "name" => 'KAB. KEPULAUAN MERANTI']);
        Regency::create(["id" => 1471, "province_id" => 14, "name" => 'KOTA PEKANBARU']);
        Regency::create(["id" => 1472, "province_id" => 14, "name" => 'KOTA DUMAI']);
        Regency::create(["id" => 1501, "province_id" => 15, "name" => 'KAB. KERINCI']);
        Regency::create(["id" => 1502, "province_id" => 15, "name" => 'KAB. MERANGIN']);
        Regency::create(["id" => 1503, "province_id" => 15, "name" => 'KAB. SAROLANGUN']);
        Regency::create(["id" => 1504, "province_id" => 15, "name" => 'KAB. BATANGHARI']);
        Regency::create(["id" => 1505, "province_id" => 15, "name" => 'KAB. MUARO JAMBI']);
        Regency::create(["id" => 1506, "province_id" => 15, "name" => 'KAB. TANJUNG JABUNG BARAT']);
        Regency::create(["id" => 1507, "province_id" => 15, "name" => 'KAB. TANJUNG JABUNG TIMUR']);
        Regency::create(["id" => 1508, "province_id" => 15, "name" => 'KAB. BUNGO']);
        Regency::create(["id" => 1509, "province_id" => 15, "name" => 'KAB. TEBO']);
        Regency::create(["id" => 1571, "province_id" => 15, "name" => 'KOTA JAMBI']);
        Regency::create(["id" => 1572, "province_id" => 15, "name" => 'KOTA SUNGAI PENUH']);
        Regency::create(["id" => 1601, "province_id" => 16, "name" => 'KAB. OGAN KOMERING ULU']);
        Regency::create(["id" => 1602, "province_id" => 16, "name" => 'KAB. OGAN KOMERING ILIR']);
        Regency::create(["id" => 1603, "province_id" => 16, "name" => 'KAB. MUARA ENIM']);
        Regency::create(["id" => 1604, "province_id" => 16, "name" => 'KAB. LAHAT']);
        Regency::create(["id" => 1605, "province_id" => 16, "name" => 'KAB. MUSI RAWAS']);
        Regency::create(["id" => 1606, "province_id" => 16, "name" => 'KAB. MUSI BANYUASIN']);
        Regency::create(["id" => 1607, "province_id" => 16, "name" => 'KAB. BANYUASIN']);
        Regency::create(["id" => 1608, "province_id" => 16, "name" => 'KAB. OGAN KOMERING ULU TIMUR']);
        Regency::create(["id" => 1609, "province_id" => 16, "name" => 'KAB. OGAN KOMERING ULU SELATAN']);
        Regency::create(["id" => 1610, "province_id" => 16, "name" => 'KAB. OGAN ILIR']);
        Regency::create(["id" => 1611, "province_id" => 16, "name" => 'KAB. EMPAT LAWANG']);
        Regency::create(["id" => 1612, "province_id" => 16, "name" => 'KAB. PENUKAL ABAB LEMATANG ILIR']);
        Regency::create(["id" => 1613, "province_id" => 16, "name" => 'KAB. MUSI RAWAS UTARA']);
        Regency::create(["id" => 1671, "province_id" => 16, "name" => 'KOTA PALEMBANG']);
        Regency::create(["id" => 1672, "province_id" => 16, "name" => 'KOTA PAGAR ALAM']);
        Regency::create(["id" => 1673, "province_id" => 16, "name" => 'KOTA LUBUK LINGGAU']);
        Regency::create(["id" => 1674, "province_id" => 16, "name" => 'KOTA PRABUMULIH']);
        Regency::create(["id" => 1701, "province_id" => 17, "name" => 'KAB. BENGKULU SELATAN']);
        Regency::create(["id" => 1702, "province_id" => 17, "name" => 'KAB. REJANG LEBONG']);
        Regency::create(["id" => 1703, "province_id" => 17, "name" => 'KAB. BENGKULU UTARA']);
        Regency::create(["id" => 1704, "province_id" => 17, "name" => 'KAB. KAUR']);
        Regency::create(["id" => 1705, "province_id" => 17, "name" => 'KAB. SELUMA']);
        Regency::create(["id" => 1706, "province_id" => 17, "name" => 'KAB. MUKO MUKO']);
        Regency::create(["id" => 1707, "province_id" => 17, "name" => 'KAB. LEBONG']);
        Regency::create(["id" => 1708, "province_id" => 17, "name" => 'KAB. KEPAHIANG']);
        Regency::create(["id" => 1709, "province_id" => 17, "name" => 'KAB. BENGKULU TENGAH']);
        Regency::create(["id" => 1771, "province_id" => 17, "name" => 'KOTA BENGKULU']);
        Regency::create(["id" => 1801, "province_id" => 18, "name" => 'KAB. LAMPUNG SELATAN']);
        Regency::create(["id" => 1802, "province_id" => 18, "name" => 'KAB. LAMPUNG TENGAH']);
        Regency::create(["id" => 1803, "province_id" => 18, "name" => 'KAB. LAMPUNG UTARA']);
        Regency::create(["id" => 1804, "province_id" => 18, "name" => 'KAB. LAMPUNG BARAT']);
        Regency::create(["id" => 1805, "province_id" => 18, "name" => 'KAB. TULANG BAWANG']);
        Regency::create(["id" => 1806, "province_id" => 18, "name" => 'KAB. TANGGAMUS']);
        Regency::create(["id" => 1807, "province_id" => 18, "name" => 'KAB. LAMPUNG TIMUR']);
        Regency::create(["id" => 1808, "province_id" => 18, "name" => 'KAB. WAY KANAN']);
        Regency::create(["id" => 1809, "province_id" => 18, "name" => 'KAB. PESAWARAN']);
        Regency::create(["id" => 1810, "province_id" => 18, "name" => 'KAB. PRINGSEWU']);
        Regency::create(["id" => 1811, "province_id" => 18, "name" => 'KAB. MESUJI']);
        Regency::create(["id" => 1812, "province_id" => 18, "name" => 'KAB. TULANG BAWANG BARAT']);
        Regency::create(["id" => 1813, "province_id" => 18, "name" => 'KAB. PESISIR BARAT']);
        Regency::create(["id" => 1871, "province_id" => 18, "name" => 'KOTA BANDAR LAMPUNG']);
        Regency::create(["id" => 1872, "province_id" => 18, "name" => 'KOTA METRO']);
        Regency::create(["id" => 1901, "province_id" => 19, "name" => 'KAB. BANGKA']);
        Regency::create(["id" => 1902, "province_id" => 19, "name" => 'KAB. BELITUNG']);
        Regency::create(["id" => 1903, "province_id" => 19, "name" => 'KAB. BANGKA SELATAN']);
        Regency::create(["id" => 1904, "province_id" => 19, "name" => 'KAB. BANGKA TENGAH']);
        Regency::create(["id" => 1905, "province_id" => 19, "name" => 'KAB. BANGKA BARAT']);
        Regency::create(["id" => 1906, "province_id" => 19, "name" => 'KAB. BELITUNG TIMUR']);
        Regency::create(["id" => 1971, "province_id" => 19, "name" => 'KOTA PANGKAL PINANG']);
        Regency::create(["id" => 2101, "province_id" => 21, "name" => 'KAB. BINTAN']);
        Regency::create(["id" => 2102, "province_id" => 21, "name" => 'KAB. KARIMUN']);
        Regency::create(["id" => 2103, "province_id" => 21, "name" => 'KAB. NATUNA']);
        Regency::create(["id" => 2104, "province_id" => 21, "name" => 'KAB. LINGGA']);
        Regency::create(["id" => 2105, "province_id" => 21, "name" => 'KAB. KEPULAUAN ANAMBAS']);
        Regency::create(["id" => 2171, "province_id" => 21, "name" => 'KOTA BATAM']);
        Regency::create(["id" => 2172, "province_id" => 21, "name" => 'KOTA TANJUNG PINANG']);
        Regency::create(["id" => 3101, "province_id" => 31, "name" => 'KAB. ADM. KEP. SERIBU']);
        Regency::create(["id" => 3171, "province_id" => 31, "name" => 'KOTA ADM. JAKARTA PUSAT']);
        Regency::create(["id" => 3172, "province_id" => 31, "name" => 'KOTA ADM. JAKARTA UTARA']);
        Regency::create(["id" => 3173, "province_id" => 31, "name" => 'KOTA ADM. JAKARTA BARAT']);
        Regency::create(["id" => 3174, "province_id" => 31, "name" => 'KOTA ADM. JAKARTA SELATAN']);
        Regency::create(["id" => 3175, "province_id" => 31, "name" => 'KOTA ADM. JAKARTA TIMUR']);
        Regency::create(["id" => 3201, "province_id" => 32, "name" => 'KAB. BOGOR']);
        Regency::create(["id" => 3202, "province_id" => 32, "name" => 'KAB. SUKABUMI']);
        Regency::create(["id" => 3203, "province_id" => 32, "name" => 'KAB. CIANJUR']);
        Regency::create(["id" => 3204, "province_id" => 32, "name" => 'KAB. BANDUNG']);
        Regency::create(["id" => 3205, "province_id" => 32, "name" => 'KAB. GARUT']);
        Regency::create(["id" => 3206, "province_id" => 32, "name" => 'KAB. TASIKMALAYA']);
        Regency::create(["id" => 3207, "province_id" => 32, "name" => 'KAB. CIAMIS']);
        Regency::create(["id" => 3208, "province_id" => 32, "name" => 'KAB. KUNINGAN']);
        Regency::create(["id" => 3209, "province_id" => 32, "name" => 'KAB. CIREBON']);
        Regency::create(["id" => 3210, "province_id" => 32, "name" => 'KAB. MAJALENGKA']);
        Regency::create(["id" => 3211, "province_id" => 32, "name" => 'KAB. SUMEDANG']);
        Regency::create(["id" => 3212, "province_id" => 32, "name" => 'KAB. INDRAMAYU']);
        Regency::create(["id" => 3213, "province_id" => 32, "name" => 'KAB. SUBANG']);
        Regency::create(["id" => 3214, "province_id" => 32, "name" => 'KAB. PURWAKARTA']);
        Regency::create(["id" => 3215, "province_id" => 32, "name" => 'KAB. KARAWANG']);
        Regency::create(["id" => 3216, "province_id" => 32, "name" => 'KAB. BEKASI']);
        Regency::create(["id" => 3217, "province_id" => 32, "name" => 'KAB. BANDUNG BARAT']);
        Regency::create(["id" => 3218, "province_id" => 32, "name" => 'KAB. PANGANDARAN']);
        Regency::create(["id" => 3271, "province_id" => 32, "name" => 'KOTA BOGOR']);
        Regency::create(["id" => 3272, "province_id" => 32, "name" => 'KOTA SUKABUMI']);
        Regency::create(["id" => 3273, "province_id" => 32, "name" => 'KOTA BANDUNG']);
        Regency::create(["id" => 3274, "province_id" => 32, "name" => 'KOTA CIREBON']);
        Regency::create(["id" => 3275, "province_id" => 32, "name" => 'KOTA BEKASI']);
        Regency::create(["id" => 3276, "province_id" => 32, "name" => 'KOTA DEPOK']);
        Regency::create(["id" => 3277, "province_id" => 32, "name" => 'KOTA CIMAHI']);
        Regency::create(["id" => 3278, "province_id" => 32, "name" => 'KOTA TASIKMALAYA']);
        Regency::create(["id" => 3279, "province_id" => 32, "name" => 'KOTA BANJAR']);
        Regency::create(["id" => 3301, "province_id" => 33, "name" => 'KAB. CILACAP']);
        Regency::create(["id" => 3302, "province_id" => 33, "name" => 'KAB. BANYUMAS']);
        Regency::create(["id" => 3303, "province_id" => 33, "name" => 'KAB. PURBALINGGA']);
        Regency::create(["id" => 3304, "province_id" => 33, "name" => 'KAB. BANJARNEGARA']);
        Regency::create(["id" => 3305, "province_id" => 33, "name" => 'KAB. KEBUMEN']);
        Regency::create(["id" => 3306, "province_id" => 33, "name" => 'KAB. PURWOREJO']);
        Regency::create(["id" => 3307, "province_id" => 33, "name" => 'KAB. WONOSOBO']);
        Regency::create(["id" => 3308, "province_id" => 33, "name" => 'KAB. MAGELANG']);
        Regency::create(["id" => 3309, "province_id" => 33, "name" => 'KAB. BOYOLALI']);
        Regency::create(["id" => 3310, "province_id" => 33, "name" => 'KAB. KLATEN']);
        Regency::create(["id" => 3311, "province_id" => 33, "name" => 'KAB. SUKOHARJO']);
        Regency::create(["id" => 3312, "province_id" => 33, "name" => 'KAB. WONOGIRI']);
        Regency::create(["id" => 3313, "province_id" => 33, "name" => 'KAB. KARANGANYAR']);
        Regency::create(["id" => 3314, "province_id" => 33, "name" => 'KAB. SRAGEN']);
        Regency::create(["id" => 3315, "province_id" => 33, "name" => 'KAB. GROBOGAN']);
        Regency::create(["id" => 3316, "province_id" => 33, "name" => 'KAB. BLORA']);
        Regency::create(["id" => 3317, "province_id" => 33, "name" => 'KAB. REMBANG']);
        Regency::create(["id" => 3318, "province_id" => 33, "name" => 'KAB. PATI']);
        Regency::create(["id" => 3319, "province_id" => 33, "name" => 'KAB. KUDUS']);
        Regency::create(["id" => 3320, "province_id" => 33, "name" => 'KAB. JEPARA']);
        Regency::create(["id" => 3321, "province_id" => 33, "name" => 'KAB. DEMAK']);
        Regency::create(["id" => 3322, "province_id" => 33, "name" => 'KAB. SEMARANG']);
        Regency::create(["id" => 3323, "province_id" => 33, "name" => 'KAB. TEMANGGUNG']);
        Regency::create(["id" => 3324, "province_id" => 33, "name" => 'KAB. KENDAL']);
        Regency::create(["id" => 3325, "province_id" => 33, "name" => 'KAB. BATANG']);
        Regency::create(["id" => 3326, "province_id" => 33, "name" => 'KAB. PEKALONGAN']);
        Regency::create(["id" => 3327, "province_id" => 33, "name" => 'KAB. PEMALANG']);
        Regency::create(["id" => 3328, "province_id" => 33, "name" => 'KAB. TEGAL']);
        Regency::create(["id" => 3329, "province_id" => 33, "name" => 'KAB. BREBES']);
        Regency::create(["id" => 3371, "province_id" => 33, "name" => 'KOTA MAGELANG']);
        Regency::create(["id" => 3372, "province_id" => 33, "name" => 'KOTA SURAKARTA']);
        Regency::create(["id" => 3373, "province_id" => 33, "name" => 'KOTA SALATIGA']);
        Regency::create(["id" => 3374, "province_id" => 33, "name" => 'KOTA SEMARANG']);
        Regency::create(["id" => 3375, "province_id" => 33, "name" => 'KOTA PEKALONGAN']);
        Regency::create(["id" => 3376, "province_id" => 33, "name" => 'KOTA TEGAL']);
        Regency::create(["id" => 3401, "province_id" => 34, "name" => 'KAB. KULON PROGO']);
        Regency::create(["id" => 3402, "province_id" => 34, "name" => 'KAB. BANTUL']);
        Regency::create(["id" => 3403, "province_id" => 34, "name" => 'KAB. GUNUNGKIDUL']);
        Regency::create(["id" => 3404, "province_id" => 34, "name" => 'KAB. SLEMAN']);
        Regency::create(["id" => 3471, "province_id" => 34, "name" => 'KOTA YOGYAKARTA']);
        Regency::create(["id" => 3501, "province_id" => 35, "name" => 'KAB. PACITAN']);
        Regency::create(["id" => 3502, "province_id" => 35, "name" => 'KAB. PONOROGO']);
        Regency::create(["id" => 3503, "province_id" => 35, "name" => 'KAB. TRENGGALEK']);
        Regency::create(["id" => 3504, "province_id" => 35, "name" => 'KAB. TULUNGAGUNG']);
        Regency::create(["id" => 3505, "province_id" => 35, "name" => 'KAB. BLITAR']);
        Regency::create(["id" => 3506, "province_id" => 35, "name" => 'KAB. KEDIRI']);
        Regency::create(["id" => 3507, "province_id" => 35, "name" => 'KAB. MALANG']);
        Regency::create(["id" => 3508, "province_id" => 35, "name" => 'KAB. LUMAJANG']);
        Regency::create(["id" => 3509, "province_id" => 35, "name" => 'KAB. JEMBER']);
        Regency::create(["id" => 3510, "province_id" => 35, "name" => 'KAB. BANYUWANGI']);
        Regency::create(["id" => 3511, "province_id" => 35, "name" => 'KAB. BONDOWOSO']);
        Regency::create(["id" => 3512, "province_id" => 35, "name" => 'KAB. SITUBONDO']);
        Regency::create(["id" => 3513, "province_id" => 35, "name" => 'KAB. PROBOLINGGO']);
        Regency::create(["id" => 3514, "province_id" => 35, "name" => 'KAB. PASURUAN']);
        Regency::create(["id" => 3515, "province_id" => 35, "name" => 'KAB. SIDOARJO']);
        Regency::create(["id" => 3516, "province_id" => 35, "name" => 'KAB. MOJOKERTO']);
        Regency::create(["id" => 3517, "province_id" => 35, "name" => 'KAB. JOMBANG']);
        Regency::create(["id" => 3518, "province_id" => 35, "name" => 'KAB. NGANJUK']);
        Regency::create(["id" => 3519, "province_id" => 35, "name" => 'KAB. MADIUN']);
        Regency::create(["id" => 3520, "province_id" => 35, "name" => 'KAB. MAGETAN']);
        Regency::create(["id" => 3521, "province_id" => 35, "name" => 'KAB. NGAWI']);
        Regency::create(["id" => 3522, "province_id" => 35, "name" => 'KAB. BOJONEGORO']);
        Regency::create(["id" => 3523, "province_id" => 35, "name" => 'KAB. TUBAN']);
        Regency::create(["id" => 3524, "province_id" => 35, "name" => 'KAB. LAMONGAN']);
        Regency::create(["id" => 3525, "province_id" => 35, "name" => 'KAB. GRESIK']);
        Regency::create(["id" => 3526, "province_id" => 35, "name" => 'KAB. BANGKALAN']);
        Regency::create(["id" => 3527, "province_id" => 35, "name" => 'KAB. SAMPANG']);
        Regency::create(["id" => 3528, "province_id" => 35, "name" => 'KAB. PAMEKASAN']);
        Regency::create(["id" => 3529, "province_id" => 35, "name" => 'KAB. SUMENEP']);
        Regency::create(["id" => 3571, "province_id" => 35, "name" => 'KOTA KEDIRI']);
        Regency::create(["id" => 3572, "province_id" => 35, "name" => 'KOTA BLITAR']);
        Regency::create(["id" => 3573, "province_id" => 35, "name" => 'KOTA MALANG']);
        Regency::create(["id" => 3574, "province_id" => 35, "name" => 'KOTA PROBOLINGGO']);
        Regency::create(["id" => 3575, "province_id" => 35, "name" => 'KOTA PASURUAN']);
        Regency::create(["id" => 3576, "province_id" => 35, "name" => 'KOTA MOJOKERTO']);
        Regency::create(["id" => 3577, "province_id" => 35, "name" => 'KOTA MADIUN']);
        Regency::create(["id" => 3578, "province_id" => 35, "name" => 'KOTA SURABAYA']);
        Regency::create(["id" => 3579, "province_id" => 35, "name" => 'KOTA BATU']);
        Regency::create(["id" => 3601, "province_id" => 36, "name" => 'KAB. PANDEGLANG']);
        Regency::create(["id" => 3602, "province_id" => 36, "name" => 'KAB. LEBAK']);
        Regency::create(["id" => 3603, "province_id" => 36, "name" => 'KAB. TANGERANG']);
        Regency::create(["id" => 3604, "province_id" => 36, "name" => 'KAB. SERANG']);
        Regency::create(["id" => 3671, "province_id" => 36, "name" => 'KOTA TANGERANG']);
        Regency::create(["id" => 3672, "province_id" => 36, "name" => 'KOTA CILEGON']);
        Regency::create(["id" => 3673, "province_id" => 36, "name" => 'KOTA SERANG']);
        Regency::create(["id" => 3674, "province_id" => 36, "name" => 'KOTA TANGERANG SELATAN']);
        Regency::create(["id" => 5101, "province_id" => 51, "name" => 'KAB. JEMBRANA']);
        Regency::create(["id" => 5102, "province_id" => 51, "name" => 'KAB. TABANAN']);
        Regency::create(["id" => 5103, "province_id" => 51, "name" => 'KAB. BADUNG']);
        Regency::create(["id" => 5104, "province_id" => 51, "name" => 'KAB. GIANYAR']);
        Regency::create(["id" => 5105, "province_id" => 51, "name" => 'KAB. KLUNGKUNG']);
        Regency::create(["id" => 5106, "province_id" => 51, "name" => 'KAB. BANGLI']);
        Regency::create(["id" => 5107, "province_id" => 51, "name" => 'KAB. KARANGASEM']);
        Regency::create(["id" => 5108, "province_id" => 51, "name" => 'KAB. BULELENG']);
        Regency::create(["id" => 5171, "province_id" => 51, "name" => 'KOTA DENPASAR']);
        Regency::create(["id" => 5201, "province_id" => 52, "name" => 'KAB. LOMBOK BARAT']);
        Regency::create(["id" => 5202, "province_id" => 52, "name" => 'KAB. LOMBOK TENGAH']);
        Regency::create(["id" => 5203, "province_id" => 52, "name" => 'KAB. LOMBOK TIMUR']);
        Regency::create(["id" => 5204, "province_id" => 52, "name" => 'KAB. SUMBAWA']);
        Regency::create(["id" => 5205, "province_id" => 52, "name" => 'KAB. DOMPU']);
        Regency::create(["id" => 5206, "province_id" => 52, "name" => 'KAB. BIMA']);
        Regency::create(["id" => 5207, "province_id" => 52, "name" => 'KAB. SUMBAWA BARAT']);
        Regency::create(["id" => 5208, "province_id" => 52, "name" => 'KAB. LOMBOK UTARA']);
        Regency::create(["id" => 5271, "province_id" => 52, "name" => 'KOTA MATARAM']);
        Regency::create(["id" => 5272, "province_id" => 52, "name" => 'KOTA BIMA']);
        Regency::create(["id" => 5301, "province_id" => 53, "name" => 'KAB. KUPANG']);
        Regency::create(["id" => 5302, "province_id" => 53, "name" => 'KAB TIMOR TENGAH SELATAN']);
        Regency::create(["id" => 5303, "province_id" => 53, "name" => 'KAB. TIMOR TENGAH UTARA']);
        Regency::create(["id" => 5304, "province_id" => 53, "name" => 'KAB. BELU']);
        Regency::create(["id" => 5305, "province_id" => 53, "name" => 'KAB. ALOR']);
        Regency::create(["id" => 5306, "province_id" => 53, "name" => 'KAB. FLORES TIMUR']);
        Regency::create(["id" => 5307, "province_id" => 53, "name" => 'KAB. SIKKA']);
        Regency::create(["id" => 5308, "province_id" => 53, "name" => 'KAB. ENDE']);
        Regency::create(["id" => 5309, "province_id" => 53, "name" => 'KAB. NGADA']);
        Regency::create(["id" => 5310, "province_id" => 53, "name" => 'KAB. MANGGARAI']);
        Regency::create(["id" => 5311, "province_id" => 53, "name" => 'KAB. SUMBA TIMUR']);
        Regency::create(["id" => 5312, "province_id" => 53, "name" => 'KAB. SUMBA BARAT']);
        Regency::create(["id" => 5313, "province_id" => 53, "name" => 'KAB. LEMBATA']);
        Regency::create(["id" => 5314, "province_id" => 53, "name" => 'KAB. ROTE NDAO']);
        Regency::create(["id" => 5315, "province_id" => 53, "name" => 'KAB. MANGGARAI BARAT']);
        Regency::create(["id" => 5316, "province_id" => 53, "name" => 'KAB. NAGEKEO']);
        Regency::create(["id" => 5317, "province_id" => 53, "name" => 'KAB. SUMBA TENGAH']);
        Regency::create(["id" => 5318, "province_id" => 53, "name" => 'KAB. SUMBA BARAT DAYA']);
        Regency::create(["id" => 5319, "province_id" => 53, "name" => 'KAB. MANGGARAI TIMUR']);
        Regency::create(["id" => 5320, "province_id" => 53, "name" => 'KAB. SABU RAIJUA']);
        Regency::create(["id" => 5321, "province_id" => 53, "name" => 'KAB. MALAKA']);
        Regency::create(["id" => 5371, "province_id" => 53, "name" => 'KOTA KUPANG']);
        Regency::create(["id" => 6101, "province_id" => 61, "name" => 'KAB. SAMBAS']);
        Regency::create(["id" => 6102, "province_id" => 61, "name" => 'KAB. MEMPAWAH']);
        Regency::create(["id" => 6103, "province_id" => 61, "name" => 'KAB. SANGGAU']);
        Regency::create(["id" => 6104, "province_id" => 61, "name" => 'KAB. KETAPANG']);
        Regency::create(["id" => 6105, "province_id" => 61, "name" => 'KAB. SINTANG']);
        Regency::create(["id" => 6106, "province_id" => 61, "name" => 'KAB. KAPUAS HULU']);
        Regency::create(["id" => 6107, "province_id" => 61, "name" => 'KAB. BENGKAYANG']);
        Regency::create(["id" => 6108, "province_id" => 61, "name" => 'KAB. LANDAK']);
        Regency::create(["id" => 6109, "province_id" => 61, "name" => 'KAB. SEKADAU']);
        Regency::create(["id" => 6110, "province_id" => 61, "name" => 'KAB. MELAWI']);
        Regency::create(["id" => 6111, "province_id" => 61, "name" => 'KAB. KAYONG UTARA']);
        Regency::create(["id" => 6112, "province_id" => 61, "name" => 'KAB. KUBU RAYA']);
        Regency::create(["id" => 6171, "province_id" => 61, "name" => 'KOTA PONTIANAK']);
        Regency::create(["id" => 6172, "province_id" => 61, "name" => 'KOTA SINGKAWANG']);
        Regency::create(["id" => 6201, "province_id" => 62, "name" => 'KAB. KOTAWARINGIN BARAT']);
        Regency::create(["id" => 6202, "province_id" => 62, "name" => 'KAB. KOTAWARINGIN TIMUR']);
        Regency::create(["id" => 6203, "province_id" => 62, "name" => 'KAB. KAPUAS']);
        Regency::create(["id" => 6204, "province_id" => 62, "name" => 'KAB. BARITO SELATAN']);
        Regency::create(["id" => 6205, "province_id" => 62, "name" => 'KAB. BARITO UTARA']);
        Regency::create(["id" => 6206, "province_id" => 62, "name" => 'KAB. KATINGAN']);
        Regency::create(["id" => 6207, "province_id" => 62, "name" => 'KAB. SERUYAN']);
        Regency::create(["id" => 6208, "province_id" => 62, "name" => 'KAB. SUKAMARA']);
        Regency::create(["id" => 6209, "province_id" => 62, "name" => 'KAB. LAMANDAU']);
        Regency::create(["id" => 6210, "province_id" => 62, "name" => 'KAB. GUNUNG MAS']);
        Regency::create(["id" => 6211, "province_id" => 62, "name" => 'KAB. PULANG PISAU']);
        Regency::create(["id" => 6212, "province_id" => 62, "name" => 'KAB. MURUNG RAYA']);
        Regency::create(["id" => 6213, "province_id" => 62, "name" => 'KAB. BARITO TIMUR']);
        Regency::create(["id" => 6271, "province_id" => 62, "name" => 'KOTA PALANGKARAYA']);
        Regency::create(["id" => 6301, "province_id" => 63, "name" => 'KAB. TANAH LAUT']);
        Regency::create(["id" => 6302, "province_id" => 63, "name" => 'KAB. KOTABARU']);
        Regency::create(["id" => 6303, "province_id" => 63, "name" => 'KAB. BANJAR']);
        Regency::create(["id" => 6304, "province_id" => 63, "name" => 'KAB. BARITO KUALA']);
        Regency::create(["id" => 6305, "province_id" => 63, "name" => 'KAB. TAPIN']);
        Regency::create(["id" => 6306, "province_id" => 63, "name" => 'KAB. HULU SUNGAI SELATAN']);
        Regency::create(["id" => 6307, "province_id" => 63, "name" => 'KAB. HULU SUNGAI TENGAH']);
        Regency::create(["id" => 6308, "province_id" => 63, "name" => 'KAB. HULU SUNGAI UTARA']);
        Regency::create(["id" => 6309, "province_id" => 63, "name" => 'KAB. TABALONG']);
        Regency::create(["id" => 6310, "province_id" => 63, "name" => 'KAB. TANAH BUMBU']);
        Regency::create(["id" => 6311, "province_id" => 63, "name" => 'KAB. BALANGAN']);
        Regency::create(["id" => 6371, "province_id" => 63, "name" => 'KOTA BANJARMASIN']);
        Regency::create(["id" => 6372, "province_id" => 63, "name" => 'KOTA BANJARBARU']);
        Regency::create(["id" => 6401, "province_id" => 64, "name" => 'KAB. PASER']);
        Regency::create(["id" => 6402, "province_id" => 64, "name" => 'KAB. KUTAI KARTANEGARA']);
        Regency::create(["id" => 6403, "province_id" => 64, "name" => 'KAB. BERAU']);
        Regency::create(["id" => 6407, "province_id" => 64, "name" => 'KAB. KUTAI BARAT']);
        Regency::create(["id" => 6408, "province_id" => 64, "name" => 'KAB. KUTAI TIMUR']);
        Regency::create(["id" => 6409, "province_id" => 64, "name" => 'KAB. PENAJAM PASER UTARA']);
        Regency::create(["id" => 6411, "province_id" => 64, "name" => 'KAB. MAHAKAM ULU']);
        Regency::create(["id" => 6471, "province_id" => 64, "name" => 'KOTA BALIKPAPAN']);
        Regency::create(["id" => 6472, "province_id" => 64, "name" => 'KOTA SAMARINDA']);
        Regency::create(["id" => 6474, "province_id" => 64, "name" => 'KOTA BONTANG']);
        Regency::create(["id" => 6501, "province_id" => 65, "name" => 'KAB. BULUNGAN']);
        Regency::create(["id" => 6502, "province_id" => 65, "name" => 'KAB. MALINAU']);
        Regency::create(["id" => 6503, "province_id" => 65, "name" => 'KAB. NUNUKAN']);
        Regency::create(["id" => 6504, "province_id" => 65, "name" => 'KAB. TANA TIDUNG']);
        Regency::create(["id" => 6571, "province_id" => 65, "name" => 'KOTA TARAKAN']);
        Regency::create(["id" => 7101, "province_id" => 71, "name" => 'KAB. BOLAANG MONGONDOW']);
        Regency::create(["id" => 7102, "province_id" => 71, "name" => 'KAB. MINAHASA']);
        Regency::create(["id" => 7103, "province_id" => 71, "name" => 'KAB. KEPULAUAN SANGIHE']);
        Regency::create(["id" => 7104, "province_id" => 71, "name" => 'KAB. KEPULAUAN TALAUD']);
        Regency::create(["id" => 7105, "province_id" => 71, "name" => 'KAB. MINAHASA SELATAN']);
        Regency::create(["id" => 7106, "province_id" => 71, "name" => 'KAB. MINAHASA UTARA']);
        Regency::create(["id" => 7107, "province_id" => 71, "name" => 'KAB. MINAHASA TENGGARA']);
        Regency::create(["id" => 7108, "province_id" => 71, "name" => 'KAB. BOLAANG MONGONDOW UTARA']);
        Regency::create(["id" => 7109, "province_id" => 71, "name" => 'KAB. KEP. SIAU TAGULANDANG BIARO']);
        Regency::create(["id" => 7110, "province_id" => 71, "name" => 'KAB. BOLAANG MONGONDOW TIMUR']);
        Regency::create(["id" => 7111, "province_id" => 71, "name" => 'KAB. BOLAANG MONGONDOW SELATAN']);
        Regency::create(["id" => 7171, "province_id" => 71, "name" => 'KOTA MANADO']);
        Regency::create(["id" => 7172, "province_id" => 71, "name" => 'KOTA BITUNG']);
        Regency::create(["id" => 7173, "province_id" => 71, "name" => 'KOTA TOMOHON']);
        Regency::create(["id" => 7174, "province_id" => 71, "name" => 'KOTA KOTAMOBAGU']);
        Regency::create(["id" => 7201, "province_id" => 72, "name" => 'KAB. BANGGAI']);
        Regency::create(["id" => 7202, "province_id" => 72, "name" => 'KAB. POSO']);
        Regency::create(["id" => 7203, "province_id" => 72, "name" => 'KAB. DONGGALA']);
        Regency::create(["id" => 7204, "province_id" => 72, "name" => 'KAB. TOLI TOLI']);
        Regency::create(["id" => 7205, "province_id" => 72, "name" => 'KAB. BUOL']);
        Regency::create(["id" => 7206, "province_id" => 72, "name" => 'KAB. MOROWALI']);
        Regency::create(["id" => 7207, "province_id" => 72, "name" => 'KAB. BANGGAI KEPULAUAN']);
        Regency::create(["id" => 7208, "province_id" => 72, "name" => 'KAB. PARIGI MOUTONG']);
        Regency::create(["id" => 7209, "province_id" => 72, "name" => 'KAB. TOJO UNA UNA']);
        Regency::create(["id" => 7210, "province_id" => 72, "name" => 'KAB. SIGI']);
        Regency::create(["id" => 7211, "province_id" => 72, "name" => 'KAB. BANGGAI LAUT']);
        Regency::create(["id" => 7212, "province_id" => 72, "name" => 'KAB. MOROWALI UTARA']);
        Regency::create(["id" => 7271, "province_id" => 72, "name" => 'KOTA PALU']);
        Regency::create(["id" => 7301, "province_id" => 73, "name" => 'KAB. KEPULAUAN SELAYAR']);
        Regency::create(["id" => 7302, "province_id" => 73, "name" => 'KAB. BULUKUMBA']);
        Regency::create(["id" => 7303, "province_id" => 73, "name" => 'KAB. BANTAENG']);
        Regency::create(["id" => 7304, "province_id" => 73, "name" => 'KAB. JENEPONTO']);
        Regency::create(["id" => 7305, "province_id" => 73, "name" => 'KAB. TAKALAR']);
        Regency::create(["id" => 7306, "province_id" => 73, "name" => 'KAB. GOWA']);
        Regency::create(["id" => 7307, "province_id" => 73, "name" => 'KAB. SINJAI']);
        Regency::create(["id" => 7308, "province_id" => 73, "name" => 'KAB. BONE']);
        Regency::create(["id" => 7309, "province_id" => 73, "name" => 'KAB. MAROS']);
        Regency::create(["id" => 7310, "province_id" => 73, "name" => 'KAB. PANGKAJENE KEPULAUAN']);
        Regency::create(["id" => 7311, "province_id" => 73, "name" => 'KAB. BARRU']);
        Regency::create(["id" => 7312, "province_id" => 73, "name" => 'KAB. SOPPENG']);
        Regency::create(["id" => 7313, "province_id" => 73, "name" => 'KAB. WAJO']);
        Regency::create(["id" => 7314, "province_id" => 73, "name" => 'KAB. SIDENRENG RAPPANG']);
        Regency::create(["id" => 7315, "province_id" => 73, "name" => 'KAB. PINRANG']);
        Regency::create(["id" => 7316, "province_id" => 73, "name" => 'KAB. ENREKANG']);
        Regency::create(["id" => 7317, "province_id" => 73, "name" => 'KAB. LUWU']);
        Regency::create(["id" => 7318, "province_id" => 73, "name" => 'KAB. TANA TORAJA']);
        Regency::create(["id" => 7322, "province_id" => 73, "name" => 'KAB. LUWU UTARA']);
        Regency::create(["id" => 7324, "province_id" => 73, "name" => 'KAB. LUWU TIMUR']);
        Regency::create(["id" => 7326, "province_id" => 73, "name" => 'KAB. TORAJA UTARA']);
        Regency::create(["id" => 7371, "province_id" => 73, "name" => 'KOTA MAKASSAR']);
        Regency::create(["id" => 7372, "province_id" => 73, "name" => 'KOTA PARE PARE']);
        Regency::create(["id" => 7373, "province_id" => 73, "name" => 'KOTA PALOPO']);
        Regency::create(["id" => 7401, "province_id" => 74, "name" => 'KAB. KOLAKA']);
        Regency::create(["id" => 7402, "province_id" => 74, "name" => 'KAB. KONAWE']);
        Regency::create(["id" => 7403, "province_id" => 74, "name" => 'KAB. MUNA']);
        Regency::create(["id" => 7404, "province_id" => 74, "name" => 'KAB. BUTON']);
        Regency::create(["id" => 7405, "province_id" => 74, "name" => 'KAB. KONAWE SELATAN']);
        Regency::create(["id" => 7406, "province_id" => 74, "name" => 'KAB. BOMBANA']);
        Regency::create(["id" => 7407, "province_id" => 74, "name" => 'KAB. WAKATOBI']);
        Regency::create(["id" => 7408, "province_id" => 74, "name" => 'KAB. KOLAKA UTARA']);
        Regency::create(["id" => 7409, "province_id" => 74, "name" => 'KAB. KONAWE UTARA']);
        Regency::create(["id" => 7410, "province_id" => 74, "name" => 'KAB. BUTON UTARA']);
        Regency::create(["id" => 7411, "province_id" => 74, "name" => 'KAB. KOLAKA TIMUR']);
        Regency::create(["id" => 7412, "province_id" => 74, "name" => 'KAB. KONAWE KEPULAUAN']);
        Regency::create(["id" => 7413, "province_id" => 74, "name" => 'KAB. MUNA BARAT']);
        Regency::create(["id" => 7414, "province_id" => 74, "name" => 'KAB. BUTON TENGAH']);
        Regency::create(["id" => 7415, "province_id" => 74, "name" => 'KAB. BUTON SELATAN']);
        Regency::create(["id" => 7471, "province_id" => 74, "name" => 'KOTA KENDARI']);
        Regency::create(["id" => 7472, "province_id" => 74, "name" => 'KOTA BAU BAU']);
        Regency::create(["id" => 7501, "province_id" => 75, "name" => 'KAB. GORONTALO']);
        Regency::create(["id" => 7502, "province_id" => 75, "name" => 'KAB. BOALEMO']);
        Regency::create(["id" => 7503, "province_id" => 75, "name" => 'KAB. BONE BOLANGO']);
        Regency::create(["id" => 7504, "province_id" => 75, "name" => 'KAB. PAHUWATO']);
        Regency::create(["id" => 7505, "province_id" => 75, "name" => 'KAB. GORONTALO UTARA']);
        Regency::create(["id" => 7571, "province_id" => 75, "name" => 'KOTA GORONTALO']);
        Regency::create(["id" => 7601, "province_id" => 76, "name" => 'KAB. PASANGKAYU']);
        Regency::create(["id" => 7602, "province_id" => 76, "name" => 'KAB. MAMUJU']);
        Regency::create(["id" => 7603, "province_id" => 76, "name" => 'KAB. MAMASA']);
        Regency::create(["id" => 7604, "province_id" => 76, "name" => 'KAB. POLEWALI MANDAR']);
        Regency::create(["id" => 7605, "province_id" => 76, "name" => 'KAB. MAJENE']);
        Regency::create(["id" => 7606, "province_id" => 76, "name" => 'KAB. MAMUJU TENGAH']);
        Regency::create(["id" => 8101, "province_id" => 81, "name" => 'KAB. MALUKU TENGAH']);
        Regency::create(["id" => 8102, "province_id" => 81, "name" => 'KAB. MALUKU TENGGARA']);
        Regency::create(["id" => 8103, "province_id" => 81, "name" => 'KAB. KEPULAUAN TANIMBAR']);
        Regency::create(["id" => 8104, "province_id" => 81, "name" => 'KAB. BURU']);
        Regency::create(["id" => 8105, "province_id" => 81, "name" => 'KAB. SERAM BAGIAN TIMUR']);
        Regency::create(["id" => 8106, "province_id" => 81, "name" => 'KAB. SERAM BAGIAN BARAT']);
        Regency::create(["id" => 8107, "province_id" => 81, "name" => 'KAB. KEPULAUAN ARU']);
        Regency::create(["id" => 8108, "province_id" => 81, "name" => 'KAB. MALUKU BARAT DAYA']);
        Regency::create(["id" => 8109, "province_id" => 81, "name" => 'KAB. BURU SELATAN']);
        Regency::create(["id" => 8171, "province_id" => 81, "name" => 'KOTA AMBON']);
        Regency::create(["id" => 8172, "province_id" => 81, "name" => 'KOTA TUAL']);
        Regency::create(["id" => 8201, "province_id" => 82, "name" => 'KAB. HALMAHERA BARAT']);
        Regency::create(["id" => 8202, "province_id" => 82, "name" => 'KAB. HALMAHERA TENGAH']);
        Regency::create(["id" => 8203, "province_id" => 82, "name" => 'KAB. HALMAHERA UTARA']);
        Regency::create(["id" => 8204, "province_id" => 82, "name" => 'KAB. HALMAHERA SELATAN']);
        Regency::create(["id" => 8205, "province_id" => 82, "name" => 'KAB. KEPULAUAN SULA']);
        Regency::create(["id" => 8206, "province_id" => 82, "name" => 'KAB. HALMAHERA TIMUR']);
        Regency::create(["id" => 8207, "province_id" => 82, "name" => 'KAB. PULAU MOROTAI']);
        Regency::create(["id" => 8208, "province_id" => 82, "name" => 'KAB. PULAU TALIABU']);
        Regency::create(["id" => 8271, "province_id" => 82, "name" => 'KOTA TERNATE']);
        Regency::create(["id" => 8272, "province_id" => 82, "name" => 'KOTA TIDORE KEPULAUAN']);
        Regency::create(["id" => 9101, "province_id" => 91, "name" => 'KAB. MERAUKE']);
        Regency::create(["id" => 9102, "province_id" => 91, "name" => 'KAB. JAYAWIJAYA']);
        Regency::create(["id" => 9103, "province_id" => 91, "name" => 'KAB. JAYAPURA']);
        Regency::create(["id" => 9104, "province_id" => 91, "name" => 'KAB. NABIRE']);
        Regency::create(["id" => 9105, "province_id" => 91, "name" => 'KAB. KEPULAUAN YAPEN']);
        Regency::create(["id" => 9106, "province_id" => 91, "name" => 'KAB. BIAK NUMFOR']);
        Regency::create(["id" => 9107, "province_id" => 91, "name" => 'KAB. PUNCAK JAYA']);
        Regency::create(["id" => 9108, "province_id" => 91, "name" => 'KAB. PANIAI']);
        Regency::create(["id" => 9109, "province_id" => 91, "name" => 'KAB. MIMIKA']);
        Regency::create(["id" => 9110, "province_id" => 91, "name" => 'KAB. SARMI']);
        Regency::create(["id" => 9111, "province_id" => 91, "name" => 'KAB. KEEROM']);
        Regency::create(["id" => 9112, "province_id" => 91, "name" => 'KAB PEGUNUNGAN BINTANG']);
        Regency::create(["id" => 9113, "province_id" => 91, "name" => 'KAB. YAHUKIMO']);
        Regency::create(["id" => 9114, "province_id" => 91, "name" => 'KAB. TOLIKARA']);
        Regency::create(["id" => 9115, "province_id" => 91, "name" => 'KAB. WAROPEN']);
        Regency::create(["id" => 9116, "province_id" => 91, "name" => 'KAB. BOVEN DIGOEL']);
        Regency::create(["id" => 9117, "province_id" => 91, "name" => 'KAB. MAPPI']);
        Regency::create(["id" => 9118, "province_id" => 91, "name" => 'KAB. ASMAT']);
        Regency::create(["id" => 9119, "province_id" => 91, "name" => 'KAB. SUPIORI']);
        Regency::create(["id" => 9120, "province_id" => 91, "name" => 'KAB. MAMBERAMO RAYA']);
        Regency::create(["id" => 9121, "province_id" => 91, "name" => 'KAB. MAMBERAMO TENGAH']);
        Regency::create(["id" => 9122, "province_id" => 91, "name" => 'KAB. YALIMO']);
        Regency::create(["id" => 9123, "province_id" => 91, "name" => 'KAB. LANNY JAYA']);
        Regency::create(["id" => 9124, "province_id" => 91, "name" => 'KAB. NDUGA']);
        Regency::create(["id" => 9125, "province_id" => 91, "name" => 'KAB. PUNCAK']);
        Regency::create(["id" => 9126, "province_id" => 91, "name" => 'KAB. DOGIYAI']);
        Regency::create(["id" => 9127, "province_id" => 91, "name" => 'KAB. INTAN JAYA']);
        Regency::create(["id" => 9128, "province_id" => 91, "name" => 'KAB. DEIYAI']);
        Regency::create(["id" => 9171, "province_id" => 91, "name" => 'KOTA JAYAPURA']);
        Regency::create(["id" => 9201, "province_id" => 92, "name" => 'KAB. SORONG']);
        Regency::create(["id" => 9202, "province_id" => 92, "name" => 'KAB. MANOKWARI']);
        Regency::create(["id" => 9203, "province_id" => 92, "name" => 'KAB. FAK FAK']);
        Regency::create(["id" => 9204, "province_id" => 92, "name" => 'KAB. SORONG SELATAN']);
        Regency::create(["id" => 9205, "province_id" => 92, "name" => 'KAB. RAJA AMPAT']);
        Regency::create(["id" => 9206, "province_id" => 92, "name" => 'KAB. TELUK BINTUNI']);
        Regency::create(["id" => 9207, "province_id" => 92, "name" => 'KAB. TELUK WONDAMA']);
        Regency::create(["id" => 9208, "province_id" => 92, "name" => 'KAB. KAIMANA']);
        Regency::create(["id" => 9209, "province_id" => 92, "name" => 'KAB. TAMBRAUW']);
        Regency::create(["id" => 9210, "province_id" => 92, "name" => 'KAB. MAYBRAT']);
        Regency::create(["id" => 9211, "province_id" => 92, "name" => 'KAB. MANOKWARI SELATAN']);
        Regency::create(["id" => 9212, "province_id" => 92, "name" => 'KAB. PEGUNUNGAN ARFAK']);
        Regency::create(["id" => 9271, "province_id" => 92, "name" => 'KOTA SORONG']);
    }
}
